services:
  - type: web
    name: coolfrog-api
    runtime: php
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan migrate --seed
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr