services:
  - type: web
    name: coolfrog-api
    runtime: docker
    env: php
    buildCommand: "./build.sh"
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_HOST
        value: your-database-host
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-user
      - key: DB_PASSWORD
        value: your-database-password